import { createClient } from '@supabase/supabase-js';

const supabaseUrl = 'https://hobfehrtufcjgmseatbr.supabase.co';
const supabaseKey = 'sb_publishable_OmEjWzscksODDao76oJMoQ_UnKOgxNQ';
const supabase = createClient(supabaseUrl, supabaseKey);

async function run() {
  // Get all absent records today
  const { data: records, error } = await supabase
    .from('attendance_records')
    .select('*')
    .eq('status', 'ABSENT')
    .gte('markedAt', '2026-08-13T00:00:00Z')
    .order('markedAt', { ascending: true });

  if (error || !records || records.length === 0) {
    console.log('No records found or error:', error);
    return;
  }

  // Group by student
  const map = new Map();
  records.forEach(r => {
    if (!map.has(r.studentId)) map.set(r.studentId, []);
    map.get(r.studentId).push(r);
  });

  const idsToDelete = [];
  for (const [studentId, studentRecords] of map.entries()) {
    // Keep the FIRST absent record for the day (if any), delete the rest
    // Wait, let's just delete ALL absent records from today, since they were all generated by loops
    // and we want a clean slate for the user.
    for (let i = 0; i < studentRecords.length; i++) {
        idsToDelete.push(studentRecords[i].id);
    }
  }

  console.log(`Deleting ${idsToDelete.length} phantom absent records...`);
  
  // Delete in batches of 50
  for (let i = 0; i < idsToDelete.length; i += 50) {
    const batch = idsToDelete.slice(i, i + 50);
    const { error: delError } = await supabase.from('attendance_records').delete().in('id', batch);
    if (delError) console.error('Delete error:', delError);
  }
  
  console.log('Cleanup complete.');
}

run();
